learnUkk/Controllers/AuthController.cs
using learnUkk.Helper;
using learnUkk.Models;
using Microsoft.AspNetCore.Components.Server.ProtectedBrowserStorage;
using Microsoft.AspNetCore.Mvc;
using System.Net;
using System.Security.Cryptography;
using System.Text;


namespace learnUkk.Controllers
{
    public class AuthController : Controller
    {
        private readonly UkkTwitterContext db;

        public AuthController(UkkTwitterContext db)
        {
            this.db = db;
        }

        public IActionResult Index()
        {
            Response.StatusCode = 200;
            return View();
        }

        public IActionResult Register()
        {
            Response.StatusCode = 200;
            return View();
        }

        public IActionResult Login()
        {
            Response.StatusCode = 200;
            return View("index");
        }

        [HttpPost]
        public async Task<ActionResult> Login(loginReq req)
        {
            //check email
            var checkEmail = db.Users.FirstOrDefault(x => x.Email == req.email);

            if(checkEmail == null)
            {
                TempData["msg"] = Core.alertMessage("Email or Password Wrong!");
                Response.StatusCode = 400;
                return View("index");
            }

            //Hash password 
            var password = string.Concat(new SHA256Managed().ComputeHash(Encoding.UTF8.GetBytes(req.password)).Select(x => x.ToString("x2")));

            //compare hashed password and password in datbase
            if(checkEmail.Password != password)
            {
                TempData["msg"] = Core.alertMessage("Email or Password Wrong!");
                Response.StatusCode = 400;
                return View("index");
            }

            //add cookies
            Response.Cookies.Append("user", checkEmail.Id.ToString());

            Response.StatusCode = 200;
            return Redirect("/Home");
        }

        [HttpPost]
        public async Task<ActionResult> Register(registerReq req)
        {
            if(req.email.Length > 50 )
            {
                TempData["msg"] = Core.alertMessage("max character emai is 50 character!");
                Response.StatusCode = 400;
                return View("Register");
            }
            if(req.username.Length > 100)
            {
                TempData["msg"] = Core.alertMessage("max character user name is 100!");
                Response.StatusCode = 400;
                return View("Register");
            }
            //check password and retype password
            if(req.password != req.retype_password)
            {
                TempData["msg"] = Core.alertMessage("Password and retype password must be same!");
                Response.StatusCode = 400;
                return View("Register");
            }

            //check email already exist
            var checkEmail = db.Users.FirstOrDefault(x => x.Email == req.email);

            if(checkEmail != null)
            {
                TempData["msg"] = "<script>alert('Email already used!');</script>";
                Response.StatusCode = 400;
                return View("Register");
            }

            //hash password
            var insertPassword = string.Concat(new SHA256Managed().ComputeHash(Encoding.UTF8.GetBytes(req.password)).Select(x => x.ToString("x2")));

            //save register data
            var obj = new User
            {
                Email = req.email,
                UserName = req.username,
                Password = insertPassword
            };

            db.Users.Add(obj);
            db.SaveChanges();

            Response.StatusCode = 200;
            return Redirect("/Home");
        }

        public async Task<ActionResult> Logout()
        {
            //remove cookie and redirect to login parth
            Response.Cookies.Delete("user");
            return Redirect("/Auth");
        }
    }
}

learnUkk/Controllers/ProfileController.cs
using learnUkk.Models;
using Microsoft.AspNetCore.Mvc;

namespace learnUkk.Controllers
{
    public class ProfileController : Controller
    {
        private readonly UkkTwitterContext db;
        public ProfileController(UkkTwitterContext db)
        {
            this.db = db;
        }

        public IActionResult Index()
        {
            //get profile data
            var user = db.Users.FirstOrDefault(x => x.Id == Convert.ToInt32(Request.Cookies["user"]));
            return View(new userProfile { Bio = user.Bio, Email = user.Email, Picture = user.Picture, userId = user.Id, userName = user.UserName});
        }

        [HttpPost]
        public async Task<ActionResult> Update(userProfile req)
        {
            //update profile data
            var user = db.Users.FirstOrDefault(x => x.Id == Convert.ToInt32(Request.Cookies["user"]));

            if (req.file != null)
            {
                var fileName = DateTime.Now.ToFileTime() + Path.GetExtension(req.file.FileName);
                using (var stream = System.IO.File.Create(Path.GetFullPath("wwwroot/images/" + fileName)))
                {
                    await req.file.CopyToAsync(stream);
                    user.Picture = fileName;
                }
            }

            user.Bio = req.Bio;
            db.SaveChanges();

            return Redirect("/Home");
        }
    }
}

learnUkk/Controllers/TweetController.cs
using learnUkk.Helper;
using learnUkk.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Runtime.InteropServices;
using System.Security.Cryptography.Xml;
using static learnUkk.Models.tweetPage;

namespace learnUkk.Controllers
{
    public class TweetController : Controller
    {
        private readonly UkkTwitterContext db;

        public TweetController(UkkTwitterContext db)
        {
            this.db = db;
        }


        [HttpPost]
        public async Task<ActionResult> Create(createPostReq req)
        {   
            if(req.tweet_text.Length > 255)
            {
                TempData["msg"] = Core.alertMessage("tweet max length is 255");
                Response.StatusCode = 400;
                return View("~/Views/Home/Create.cshtml");
            }
            //check user
            string? fileName = null;
            var user = db.Users.FirstOrDefault(x => x.Id == Convert.ToInt32(Request.Cookies["user"]));
            if (user == null)
            {
                return NotFound("User not found.");
            }
            //save data
            if(req.file != null)
            {
                fileName = DateTime.Now.ToFileTime() + Path.GetExtension(req.file.FileName);
                using (var stream = System.IO.File.Create(Path.GetFullPath("wwwroot/images/" +  fileName)))
                {
                    await req.file.CopyToAsync(stream);
                }
            }
            var tag_tweet = req.tweet_text.Split(' ').Where(x => x.Contains("#")).ToList();
            tag_tweet.ForEach(x =>
            {
                var checkTag = db.Tags.FirstOrDefault(y => y.Name == x);
                if (checkTag == null)
                {
                    db.Tags.Add(new Tag
                    {
                        Name = x.ToString()
                    });

                    db.SaveChanges();
                }
            });

            //save tweets

            db.Tweets.Add(new Tweet
            {
                Tweet1 = req.tweet_text,
                UserId = user.Id,
                Picture = fileName
            });

            await db.SaveChangesAsync();

            var twets = db.Tweets.OrderByDescending(x => x.Id).FirstOrDefault();

            tag_tweet.ForEach(x =>
            {
                var checkTag = db.Tags.FirstOrDefault(y => y.Name == x);

                db.TagTweets.Add(new TagTweet
                {
                    TweetId = twets.Id,
                    TagId = checkTag.Id
                });
                db.SaveChanges();
            });

            //save
            db.SaveChanges();
            Response.StatusCode = 200;
            return Redirect("/Home");
        }

        [HttpPost]
        public async Task<ActionResult> Comment(tweetPage req)
        {
            if (req.commentPostReq.tweet_text.Length > 255)
            {
                TempData["msg"] = Core.alertMessage("Comment max length is 255");
                Response.StatusCode = 400;
                return Redirect("/Home");
            }
            //check user
            string? fileName = null;
            var user = db.Users.FirstOrDefault(x => x.Id == Convert.ToInt32(Request.Cookies["user"]));
            if (user == null)
            {
                return NotFound("User not found.");
            }

            //save image
            if (req.commentPostReq.file != null)
            {
                fileName = DateTime.Now.ToFileTime() + Path.GetExtension(req.commentPostReq.file.FileName);
                using (var stream = System.IO.File.Create(Path.GetFullPath("wwwroot/images/" + fileName)))
                {
                    await req.commentPostReq.file.CopyToAsync(stream);
                }
            }

            //save tag
            var tag_comment = req.commentPostReq.tweet_text.Split(' ').Where(x => x.Contains("#")).ToList();
            tag_comment.ForEach(x =>
            {
                var checkTag = db.Tags.FirstOrDefault(y => y.Name == x);
                if (checkTag == null)
                {
                    db.Tags.Add(new Tag
                    {
                        Name = x.ToString()
                    });

                    db.SaveChanges();
                }
            });

            db.Comments.Add(new Comment
            {
                TweetId = req.commentPostReq.tweetId,
                Comment1 = req.commentPostReq.tweet_text,
                UserId = user.Id,
                Picture = fileName
            });

            await db.SaveChangesAsync();

            var comment = db.Tweets.OrderByDescending(x => x.Id).FirstOrDefault();

            //add comment tag
            tag_comment.ForEach(x =>
            {
                var checkTag = db.Tags.FirstOrDefault(y => y.Name == x);

                db.TagComments.Add(new TagComment
                {
                    CommentId = comment.Id,
                    TagId = checkTag.Id
                });
                db.SaveChanges();
            });

            //save
            db.SaveChanges();
            Response.StatusCode = 200;
            return Redirect("/Home");
        }

        [HttpPost]
        public async Task<ActionResult> Search(tweetPage search)
        {

            if(search.searchString == null)
            {
                return Redirect("/Home");
            }

            var tweetData = new List<tweetShow>();

            db.Tweets.Include(x => x.User).Include(x => x.TagTweets).ThenInclude(x => x.Tag).Include(x => x.Comments).ThenInclude(x => x.User).Include(x => x.Comments).ThenInclude(x => x.TagComments).ThenInclude(x => x.Tag).ToList().Where(x => x.TagTweets.ToList().Where(i => i.Tag.Name.ToLower().Contains(search.searchString.ToLower())).Any() || x.Comments.ToList().Where(i => i.TagComments.Where(j => j.Tag.Name.ToLower().Contains(search.searchString.ToLower())).Any()).Any()).ToList().ForEach(x =>
            {
                var listTagTweet = new List<tag>();
                var commentList = new List<commentShow>();

                x.Comments.ToList().ForEach(y =>
                {
                    var listTagComment = new List<tag>();
                    listTagComment.AddRange(y.TagComments.Select(z => new tag { Name = z.Tag.Name }));

                    commentList.Add(new commentShow
                    {
                        Comment1 = y.Comment1,
                        Picture = y.Picture,
                        User = new userShow { userId = y.User.Id, Email = y.User.Email, userName = y.User.UserName, Bio = y.User.Bio, Picture = y.User.Picture },
                        Tag = listTagComment
                    });

                });

                listTagTweet.AddRange(x.TagTweets.Select(y => new tag { Name = y.Tag.Name }));

                tweetData.Add(new tweetShow
                {
                    idTweet = x.Id,
                    Tweet1 = x.Tweet1,
                    User = new userShow { userId = x.User.Id, Email = x.User.Email, userName = x.User.UserName, Bio = x.User.Bio, Picture = x.User.Picture },
                    Picture = x.Picture,
                    Tag = listTagTweet,
                    CommentList = commentList
                });
            });

            Response.StatusCode = 200;
            return View("~/Views/Home/index.cshtml", new tweetPage { tweetData = tweetData });
        }

        [HttpPost]
        public async Task<ActionResult> EditTweet(tweetPage req)
        {
            var tweet = db.Tweets.Include(x => x.User).FirstOrDefault(x => x.Id == req.editTweetId);

            Response.StatusCode = 200;
            return View("~/Views/Home/EditTweet.cshtml", new editTweet { idTweet = tweet.Id, Picture = tweet.Picture, Tweet1 = tweet.Tweet1, User = new userShow { Bio = tweet.User.Bio, Email = tweet.User.Email, userId = tweet.User.Id, Picture = tweet.User.Picture, userName = tweet.User.UserName } });
        }

        [HttpPost]
        public async Task<ActionResult> EditComment(tweetPage req)
        {
            var comment = db.Comments.Include(x => x.User).FirstOrDefault(x => x.Id == req.editCommentId);

            Response.StatusCode = 200;
            return View("~/Views/Home/EditComment.cshtml", new editComment { idComment = comment.Id, Picture = comment.Picture, Comment1 = comment.Comment1 });
        }

        [HttpPost]
        public async Task<ActionResult> EditTweetPost(editTweet req)
        {
            if(req.Tweet1.Length > 255)
            {
                TempData["msg"] = Core.alertMessage("Password and retype password must be same!");
                Response.StatusCode = 400;
                return Redirect("/Home");
            }

            var tweet = db.Tweets.Include(x => x.User).FirstOrDefault(x => x.Id == req.idTweet);

            tweet.Tweet1 = req.Tweet1;

            if (req.file != null)
            {
                var fileName = DateTime.Now.ToFileTime() + Path.GetExtension(req.file.FileName);
                using (var stream = System.IO.File.Create(Path.GetFullPath("wwwroot/images/" + fileName)))
                {
                    await req.file.CopyToAsync(stream);
                    tweet.Picture = fileName;
                }
            }

            db.TagTweets.RemoveRange(tweet.TagTweets.ToList());
            db.SaveChanges();

            var tag_tweets = req.Tweet1.Split(' ').Where(x => x.Contains("#")).ToList();
            tag_tweets.ForEach(x =>
            {
                var checkTag = db.Tags.FirstOrDefault(y => y.Name == x);
                if (checkTag == null)
                {
                    db.Tags.Add(new Tag
                    {
                        Name = x.ToString()
                    });

                    db.SaveChanges();
                }
            });

            tag_tweets.ForEach(x =>
            {
                var checkTag = db.Tags.FirstOrDefault(y => y.Name == x);

learnUkk/Views/Home/Create.cshtml
@model learnUkk.Models.createPostReq
@{
    ViewData["Title"] = "Create";

    //check response code
    if (Context.Response.StatusCode.ToString().First() != '2')
    {
        @Html.Raw(TempData["msg"])
    }

    var checkAuth = Context.Request.Cookies["user"];
    if (string.IsNullOrEmpty(checkAuth))
    {
        Context.Response.Redirect("/Auth");
    }
}

<div class="card col-lg-6 mx-auto mt-2" >
    <form class="card-body d-flex flex-column" enctype="multipart/form-data" asp-controller="Tweet" asp-action="Create">
        <img id="imagePreview"/>
        <input type="text" class="my-2" asp-for="tweet_text"/>
        <input type="file" asp-for="file"  class="input-group-prepend my-2" id="inputImage" accept="image/jpg, image/jpeg" />
        <button type="submit" class="btn btn-primary">Post</button>
    </form>
</div>

<script>
    //Get the button and image
    let uploadButton = document.getElementById("inputImage");
    let imagePriview = document.getElementById("imagePreview");

    uploadButton.onchange = () => {
        //reader and set src atribute to img
        let reader = new FileReader();
        reader.readAsDataURL(uploadButton.files[0]);
        console.log(uploadButton.files[0]);
        reader.onload = () => {
            imagePriview.setAttribute("src", reader.result);
        }
    }
</script>

learnUkk/Views/Home/EditComment.cshtml
@model learnUkk.Models.editComment
@{
    ViewData["Title"] = "Edit Comment";

    //check response code
    if (Context.Response.StatusCode.ToString().First() != '2')
    {
        @Html.Raw(TempData["msg"])
    }

    var checkAuth = Context.Request.Cookies["user"];
    if (string.IsNullOrEmpty(checkAuth))
    {
        Context.Response.Redirect("/Auth");
    }
}

<div class="card col-lg-6 mx-auto mt-2">
    <form class="card-body d-flex flex-column" enctype="multipart/form-data" asp-controller="Tweet" asp-action="EditCommentPost">
        <img id="imagePreview" src="~/images/@Model.Picture" />
        <input type="hidden" value="@Model.idComment" asp-for="idComment" />
        <input type="text" class="my-2" asp-for="Comment1" value="@Model.Comment1" />
        <input type="file" asp-for="file" class="input-group-prepend my-2" id="inputImage" accept="image/jpg, image/jpeg" />
        <button type="submit" class="btn btn-warning">Edit</button>
    </form>
</div>

<script>
    //Get the button and image
    let uploadButton = document.getElementById("inputImage");
    let imagePriview = document.getElementById("imagePreview");

    uploadButton.onchange = () => {
        //reader and set src atribute to img
        let reader = new FileReader();
        reader.readAsDataURL(uploadButton.files[0]);
        console.log(uploadButton.files[0]);
        reader.onload = () => {
            imagePriview.setAttribute("src", reader.result);
        }
    }
</script>

learnUkk/Views/Home/EditTweet.cshtml
@model learnUkk.Models.editTweet
@{
    ViewData["Title"] = "Edit Tweet";

    //check response code
    if (Context.Response.StatusCode.ToString().First() != '2')
    {
        @Html.Raw(TempData["msg"])
    }

    var checkAuth = Context.Request.Cookies["user"];
    if (string.IsNullOrEmpty(checkAuth))
    {
        Context.Response.Redirect("/Auth");
    }
}

<div class="card col-lg-6 mx-auto mt-2">
    <form class="card-body d-flex flex-column" enctype="multipart/form-data" asp-controller="Tweet" asp-action="EditTweetPost">
        <img id="imagePreview" src="~/images/@Model.Picture" />
        <input type="hidden" value="@Model.idTweet" asp-for="idTweet" />
        <input type="text" class="my-2" asp-for="Tweet1" value="@Model.Tweet1" />
        <input type="file" asp-for="file" class="input-group-prepend my-2" id="inputImage" accept="image/jpg, image/jpeg" />
        <button type="submit" class="btn btn-warning">Edit</button>
    </form>
</div>

<script>
    //Get the button and image
    let uploadButton = document.getElementById("inputImage");
    let imagePriview = document.getElementById("imagePreview");

    uploadButton.onchange = () => {
        //reader and set src atribute to img
        let reader = new FileReader();
        reader.readAsDataURL(uploadButton.files[0]);
        console.log(uploadButton.files[0]);
        reader.onload = () => {
            imagePriview.setAttribute("src", reader.result);
        }
    }
</script>

learnUkk/Views/Home/Index.cshtml
@model learnUkk.Models.tweetPage

@{
    ViewData["Title"] = "Home Page";

    //check response code
    if (Context.Response.StatusCode.ToString().First() != '2')
    {
        @Html.Raw(TempData["msg"])
    } 

    var checkAuth = Context.Request.Cookies["user"];
    if (string.IsNullOrEmpty(checkAuth))
    {
        Context.Response.Redirect("/Auth");
    }
}

<div class="conatainer col-lg-12 d-flex mt-1">
    <div class="col-lg-3 d-flex flex-column">
        <img class="nav-link text-dark logo" src="~/images/logo-twitter.png" />
        <a class="nav-link text-dark" asp-controller="Home" asp-action="index">Home</a>
        <a class="nav-link text-dark"  asp-controller="Profile" asp-action="index">Profile</a>
        <a class="nav-link text-dark" asp-controller="Auth" asp-action="Logout">Logout</a>
    </div>
     <div class="col-lg-6 ">
        <div class="d-flex justify-content-between">
            <form class="d-flex flex-column col-lg-8" asp-controller="Tweet" asp-action="Search">
            <input type="text" class="p-1" asp-for="searchString" placeholder="Search" />
            </form>
            <a class="col-lg-3 btn btn-primary" asp-controller="Home" asp-action="Create">Create new</a>
        </div>
        <div class="d-flex flex-column">
            @foreach (var item in Model.tweetData)
            {
                <div class="card mt-2"> 
                <div class="card-body"> 
                    <div class="d-flex align-items-center justify-content-between">
                        <div class="d-flex align-items-center">
                            @if(item.User.Picture == null)
                            {
                                <img src="~/images/dafault-profile-image.png" class="rounded-circle img-profile border mx-2">
                            }
                            else{
                                <img src="~/images/@item.User.Picture" class="rounded-circle img-profile border mx-2">
                            }
                            <span>@item.User.userName</span>
                        </div>
                        @if (item.User.userId == Convert.ToInt32(Context.Request.Cookies["user"]))
                        {
                            <div class="d-flex">
                                <form class="d-flex flex-column" asp-controller="Tweet" asp-action="EditTweet">
                                    <input type="hidden" value="@item.idTweet" asp-for="editTweetId" />
                                    <button class="btn btn-warning mx-2">Edit</button>
                                </form>
                                <form class="d-flex flex-column" asp-controller="Tweet" asp-action="DeleteTweet">
                                    <input type="hidden" value="@item.idTweet" asp-for="editTweetId" />
                                    <button class="btn btn-danger">Delete</button>
                                </form>
                            </div>
                        }
                    </div>
                    <div class="d-flex flex-column">
                        @if (item.Picture != null)
                        {
                            <img src="~/images/@item.Picture" class="img-fluid my-2" >
                        }
                        <span>@item.Tweet1</span><br />
                        <span class="my-4 ms-4">Comment</span>
                            <div class="ms-4 card">
                                <div class="card-body">
                                    <form class="d-flex flex-column" enctype="multipart/form-data" asp-controller="Tweet" asp-action="Comment">
                                        <img id="imagePreview-@item.idTweet" class="img-fluid my-2" />
                                       <div class="d-flex justify-content-between">
                                           <input type="hidden" asp-for="commentPostReq.tweetId" value="@item.idTweet"/>
                                            <input type="text" asp-for="commentPostReq.tweet_text" class="col-lg-9 mr-1" />
                                            <input type="file" asp-for="commentPostReq.file" class="input-group-prepend input-file-comment" id="inputImage-@item.idTweet" accept="image/jpg, image/jpeg">
                                            <label for="inputImage-@item.idTweet" class="btn btn-primary col-lg-3  mx-2">Upload Image</label>
                                        </div>
                                        <button type="submit" class="btn btn-primary mt-2">Comment</button>
                                    </form>
                                </div>
                            </div>
                        </div>
                         @foreach(var comment in item.CommentList)
                            {
                            <div class="ms-4 card my-2">
                                <div class="card-body">
                                   <div class="d-flex align-items-center justify-content-between">
                                        <div class="d-flex align-items-center">
                                            @if(comment.User.Picture == null)
                                            {
                                                <img src="~/images/dafault-profile-image.png" class="rounded-circle img-profile border mx-2">
                                            }
                                            else{
                                                <img src="~/images/@comment.User.Picture" class="rounded-circle img-profile border mx-2">
                                            }
                                            <span>@comment.User.userName</span>
                                        </div>
                                        @if (comment.User.userId == Convert.ToInt32(Context.Request.Cookies["user"]))
                                        {
                                            <div class="d-flex">
                                                <form class="d-flex flex-column mx-2" asp-controller="Tweet" asp-action="EditComment">
                                                    <input type="hidden" value="@comment.CommentId" asp-for="editCommentId" />
                                                    <button class="btn btn-warning">Edit</button>
                                                </form>
                                                <form class="d-flex flex-column" asp-controller="Tweet" asp-action="DeleteComment">
                                                    <input type="hidden" value="@comment.CommentId" asp-for="editCommentId" />
                                                    <button class="btn btn-danger">Delete</button>
                                                </form>
                                            </div>
                                        }
                                    </div>
                                    @if (comment.Picture != null)
                                    {
                                        <img src="~/images/@comment.Picture" class="img-fluid my-2" ><br />
                                    }
                                    <span>@comment.Comment1</span><br />
                                </div>
                            </div>
                            }
                    </div>
                </div>
            }
        </div>
        </div>
</div>
<style>
    .img-profile{
        width: 30px;
        height: 30px;
    }
    input[type="file"]
    {
        display: none;
    }
    .logo{
        width: 100px;
        height: auto;
    }
</style>
    <script>
        const uploadButton = document.querySelectorAll(".input-file-comment");

        uploadButton.forEach((el) => {
            el.addEventListener('change', (ev) => {
                const target = ev.currentTarget;
                const file = target.files[0];
                if (!file) return;

                const id = el.id.split('-')[1];
                const previewEl = document.querySelector(`#imagePreview-${id}`);

                if (!previewEl) return;

                previewEl.src = URL.createObjectURL(file);
            });
        });
    </script>